### ISSUE TITLE
Issue : TypeError: forward() got an unexpected keyword argument 'pre_sample_ofst'

### ISSUE THREAD

**Issue by Kunaldargan** [rajatkoner08/InstanceFormer#1]
python -u inference.py --img_path ./ytvis/val/JPEGImages --ann_path ./ytvis/annotations/instances_val_sub.json --initial_output_dir ./outputs_ytvis2021 --backbone resnet50 --masks --with_box_refine --rel_coord --weighted_category --exp_name r50_ytvis_21 --propagate_ref_points --propagate_class --increase_proposals 5 --ckpt_name r50_ytvis_21.pth
Initi main
Initi parse
cuda
['./outputs_ytvis2021/experiments/r50_ytvis_21/r50_ytvis_21.pth']
Processing checkpoint :  r50_ytvis_21
  0%|                                                                                                                                                             | 0/421 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 270, in <module>
    main(args)
  File "inference.py", line 140, in main
    outputs = model.inference(img, img.shape[-1], img.shape[-2], all_token_mem, all_mask, memory_pos,
  File "/DATA/scratch/kunal/Projects/baselines/video_instance_segmentation/InstanceFormer/models/online_segmentation.py", line 345, in inference
    enc_inter_outputs_class, enc_inter_outputs_coord, sampling_locations_all= self.detr.transformer(frame_lbl_src, frame_lbl_mask, frame_lbl_pos, query_embed,
  File "/home/kunal/anaconda3/envs/INSTANCEFORMER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATA/scratch/kunal/Projects/baselines/video_instance_segmentation/InstanceFormer/models/deformable_transformer.py", line 201, in forward
    = self.encoder(src_flatten, spatial_shapes, level_start_index, valid_ratios,
  File "/home/kunal/anaconda3/envs/INSTANCEFORMER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATA/scratch/kunal/Projects/baselines/video_instance_segmentation/InstanceFormer/models/deformable_transformer.py", line 376, in forward
    tgt, sampling_locations = layer(output, pos, reference_points, spatial_shapes, level_start_index,
  File "/home/kunal/anaconda3/envs/INSTANCEFORMER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATA/scratch/kunal/Projects/baselines/video_instance_segmentation/InstanceFormer/models/deformable_transformer.py", line 299, in forward
    src2, sampling_locations = self.self_attn(self.with_pos_embed(src, pos), None, reference_points, src, spatial_shapes,
  File "/home/kunal/anaconda3/envs/INSTANCEFORMER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'pre_sample_ofst'

Tried to run inference over ytvis 2021 dataset. Got this error.
Thank you for the great code. It is essential for me to be able to reproduce the results.
Please update

**Comment by Tanveer81** [comment]
Thank you for pointing out the bug. The deformable attention module is updated.
