### ISSUE TITLE
 bash configs/pretrain_r50.sh  ：KeyError: 'matcher_label' and 

### ISSUE THREAD

**Issue by wanghongkai** [rajatkoner08/InstanceFormer#3]
+ python -u main.py --coco_path /database/whk/coco --num_frames 1 --memory_support 1 --dataset_file coco --backbone resnet50 --masks --with_box_refine --rel_coord --epochs 12 --lr 1e-4 --lr_drop 4 10 --exp_name r50_pretrain --batch_size 4
Not using distributed mode
number of params: 42724653
loading annotations into memory...
Done (t=15.91s)
creating index...
index created!
loading annotations into memory...
Done (t=0.56s)
creating index...
index created!
Start training
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 256, in <module>
    main(args)
  File "main.py", line 199, in main
    train_stats = train_one_epoch(model, criterion, data_loader_train, optimizer, device, epoch, args.clip_max_norm,
  File "/media/M2021/wanghongkai/whk/InstanceFormer/engine.py", line 57, in train_one_epoch
    outputs, loss_dict = model(samples, targets, criterion)  # freeze_detr=False
  File "/media/M2021/wanghongkai/whk/anaconda3/envs/instanceformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/M2021/wanghongkai/whk/InstanceFormer/models/online_segmentation.py", line 128, in forward
    o_classes, o_cord, o_maks, top_mem, t_classes, supcon_ind, all_indices, idx_permute = transformer_postprocess(self, hs,memory, init_reference,
  File "/media/M2021/wanghongkai/whk/InstanceFormer/models/segmentation_helper.py", line 118, in transformer_postprocess
    indices = criterion.matcher(outputs_layer, gt_targets, frame, valid_ratios)  # todo check matching dat includes all frames
  File "/media/M2021/wanghongkai/whk/anaconda3/envs/instanceformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/M2021/wanghongkai/whk/InstanceFormer/models/matcher.py", line 51, in forward
    tgt_ids = torch.cat([v["matcher_label"][nf] for v in targets])
  File "/media/M2021/wanghongkai/whk/InstanceFormer/models/matcher.py", line 51, in <listcomp>
    tgt_ids = torch.cat([v["matcher_label"][nf] for v in targets])
KeyError: 'matcher_label'

**Comment by Tanveer81** [comment]
The "matcher_label" does not exist for COCO dataset. Can you comment that line and run it. We will update the repository. 
The pretraining is not necessary as the pretained weights are already available at this [link](https://drive.google.com/drive/u/3/folders/1uAvjjIukcugt7JkCK8KiHQnnoJd0Hgsj).
